### ISSUE TITLE
Traceback (most recent call last):   File "C:\..b\site-packages\openbabel.py", line 22, in swig_import_helper     return importlib.import_module(mname)

### ISSUE THREAD

**Issue by MCBoos** [patrickfuller/blender-chemicals#5]
![image](https://user-images.githubusercontent.com/12481285/57964296-7d28e280-7965-11e9-999b-4e6a14bfe061.png)
C:\Users\15020>python -m blender_chemicals.run c1ccccc1
Traceback (most recent call last):
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\site-packages\openbabel.py", line 22, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\site-packages\blender_chemicals\run.py", line 10, in <module>
    import pybel
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\site-packages\pybel.py", line 53, in <module>
    import openbabel as ob
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\site-packages\openbabel.py", line 25, in <module>
    _openbabel = swig_import_helper()
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\site-packages\openbabel.py", line 24, in swig_import_helper
    return importlib.import_module('_openbabel')
  File "C:\Users\15020\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: 找不到指定的程序。

C:\Users\15020>

**Comment by MCBoos** [comment]
please help me thanks very much

**Comment by patrickfuller** [comment]
Hi,

I have to guess because I don't have a windows computer.

My guess from `ImportError: DLL load failed: 找不到指定的程序。` is that open babel is not installed properly. This is a common issue, especially on windows. If you need to get this running, I recommend uninstalling your python environment and then installing [miniconda](https://docs.conda.io/en/latest/miniconda.html). You should then be able to run `conda install -c openbabel openbabel` to install open babel properly.

Hope this helps,
Pat
